import { Timesheet, TimesheetEntry } from '@/types/timesheet';
import { calculateTotalHours, getTimesheetStatus } from '@/lib/utils/status';

function createInitialTimesheets(): Timesheet[] {
  const timesheetData: Array<{
    id: string;
    weekNumber: number;
    year: number;
    startDate: string;
    endDate: string;
    entries: TimesheetEntry[];
  }> = [
    {
      id: 'ts-week-1',
      weekNumber: 1,
      year: 2024,
      startDate: '2024-01-01',
      endDate: '2024-01-05',
      entries: [
        {
          id: 'ent-1-1',
          timesheetId: 'ts-week-1',
          date: '2024-01-01',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-1-2',
          timesheetId: 'ts-week-1',
          date: '2024-01-01',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-1-3',
          timesheetId: 'ts-week-1',
          date: '2024-01-02',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-1-4',
          timesheetId: 'ts-week-1',
          date: '2024-01-02',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Code Review',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-1-5',
          timesheetId: 'ts-week-1',
          date: '2024-01-03',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-1-6',
          timesheetId: 'ts-week-1',
          date: '2024-01-03',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Testing',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-1-7',
          timesheetId: 'ts-week-1',
          date: '2024-01-04',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-1-8',
          timesheetId: 'ts-week-1',
          date: '2024-01-04',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Meeting',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-1-9',
          timesheetId: 'ts-week-1',
          date: '2024-01-05',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-1-10',
          timesheetId: 'ts-week-1',
          date: '2024-01-05',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Bug fixes',
          description: 'Homepage Development',
          hours: 4,
        },
      ],
    },
    {
      id: 'ts-week-2',
      weekNumber: 2,
      year: 2024,
      startDate: '2024-01-08',
      endDate: '2024-01-12',
      entries: [
        {
          id: 'ent-2-1',
          timesheetId: 'ts-week-2',
          date: '2024-01-08',
          projectId: 'proj-3',
          projectName: 'Dashboard Development',
          workType: 'Feature Development',
          description: 'Dashboard layout & chart components',
          hours: 8,
        },
        {
          id: 'ent-2-2',
          timesheetId: 'ts-week-2',
          date: '2024-01-09',
          projectId: 'proj-3',
          projectName: 'Dashboard Development',
          workType: 'Feature Development',
          description: 'API client integration',
          hours: 8,
        },
        {
          id: 'ent-2-3',
          timesheetId: 'ts-week-2',
          date: '2024-01-10',
          projectId: 'proj-4',
          projectName: 'API Integration',
          workType: 'Feature Development',
          description: 'Endpoint error handling & contracts',
          hours: 8,
        },
        {
          id: 'ent-2-4',
          timesheetId: 'ts-week-2',
          date: '2024-01-11',
          projectId: 'proj-4',
          projectName: 'API Integration',
          workType: 'Testing',
          description: 'Unit & integration test setup',
          hours: 8,
        },
        {
          id: 'ent-2-5',
          timesheetId: 'ts-week-2',
          date: '2024-01-12',
          projectId: 'proj-5',
          projectName: 'Bug Fixes',
          workType: 'Bug fixes',
          description: 'Sprint bug triage and resolutions',
          hours: 8,
        },
      ],
    },
    {
      id: 'ts-week-3',
      weekNumber: 3,
      year: 2024,
      startDate: '2024-01-15',
      endDate: '2024-01-19',
      entries: [
        {
          id: 'ent-3-1',
          timesheetId: 'ts-week-3',
          date: '2024-01-15',
          projectId: 'proj-2',
          projectName: 'Mobile App',
          workType: 'Feature Development',
          description: 'Mobile navigation drawer',
          hours: 6,
        },
        {
          id: 'ent-3-2',
          timesheetId: 'ts-week-3',
          date: '2024-01-16',
          projectId: 'proj-2',
          projectName: 'Mobile App',
          workType: 'Feature Development',
          description: 'Authentication screen implementation',
          hours: 6,
        },
        {
          id: 'ent-3-3',
          timesheetId: 'ts-week-3',
          date: '2024-01-17',
          projectId: 'proj-5',
          projectName: 'Bug Fixes',
          workType: 'Bug fixes',
          description: 'Fix input autofocus on mobile devices',
          hours: 4,
        },
      ],
    },
    {
      id: 'ts-week-4',
      weekNumber: 4,
      year: 2024,
      startDate: '2024-01-22',
      endDate: '2024-01-26',
      entries: [
        {
          id: 'ent-4-1',
          timesheetId: 'ts-week-4',
          date: '2024-01-22',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-4-2',
          timesheetId: 'ts-week-4',
          date: '2024-01-22',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-4-3',
          timesheetId: 'ts-week-4',
          date: '2024-01-23',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-4-4',
          timesheetId: 'ts-week-4',
          date: '2024-01-23',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-4-5',
          timesheetId: 'ts-week-4',
          date: '2024-01-23',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-4-6',
          timesheetId: 'ts-week-4',
          date: '2024-01-24',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-4-7',
          timesheetId: 'ts-week-4',
          date: '2024-01-24',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-4-8',
          timesheetId: 'ts-week-4',
          date: '2024-01-24',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-4-9',
          timesheetId: 'ts-week-4',
          date: '2024-01-25',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
        {
          id: 'ent-4-10',
          timesheetId: 'ts-week-4',
          date: '2024-01-25',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Homepage Development',
          hours: 4,
        },
      ],
    },
    {
      id: 'ts-week-5',
      weekNumber: 5,
      year: 2024,
      startDate: '2024-01-28',
      endDate: '2024-02-01',
      entries: [],
    },
    {
      id: 'ts-week-6',
      weekNumber: 6,
      year: 2024,
      startDate: '2024-02-04',
      endDate: '2024-02-08',
      entries: [
        {
          id: 'ent-6-1',
          timesheetId: 'ts-week-6',
          date: '2024-02-04',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Feature Development',
          description: 'Hero section revamp',
          hours: 8,
        },
        {
          id: 'ent-6-2',
          timesheetId: 'ts-week-6',
          date: '2024-02-05',
          projectId: 'proj-2',
          projectName: 'Mobile App',
          workType: 'Feature Development',
          description: 'Push notification handler',
          hours: 8,
        },
        {
          id: 'ent-6-3',
          timesheetId: 'ts-week-6',
          date: '2024-02-06',
          projectId: 'proj-3',
          projectName: 'Dashboard Development',
          workType: 'Feature Development',
          description: 'Data export modal & CSV generator',
          hours: 8,
        },
        {
          id: 'ent-6-4',
          timesheetId: 'ts-week-6',
          date: '2024-02-07',
          projectId: 'proj-4',
          projectName: 'API Integration',
          workType: 'Feature Development',
          description: 'OAuth2 refresh token flow',
          hours: 8,
        },
        {
          id: 'ent-6-5',
          timesheetId: 'ts-week-6',
          date: '2024-02-08',
          projectId: 'proj-6',
          projectName: 'Design System',
          workType: 'Code Review',
          description: 'Typography tokens audit',
          hours: 8,
        },
      ],
    },
    {
      id: 'ts-week-7',
      weekNumber: 7,
      year: 2024,
      startDate: '2024-02-11',
      endDate: '2024-02-15',
      entries: [
        {
          id: 'ent-7-1',
          timesheetId: 'ts-week-7',
          date: '2024-02-11',
          projectId: 'proj-1',
          projectName: 'Homepage Development',
          workType: 'Meeting',
          description: 'Sprint planning and scoping',
          hours: 4,
        },
        {
          id: 'ent-7-2',
          timesheetId: 'ts-week-7',
          date: '2024-02-12',
          projectId: 'proj-5',
          projectName: 'Bug Fixes',
          workType: 'Bug fixes',
          description: 'Fix sticky header flicker on Safari',
          hours: 6,
        },
        {
          id: 'ent-7-3',
          timesheetId: 'ts-week-7',
          date: '2024-02-13',
          projectId: 'proj-3',
          projectName: 'Dashboard Development',
          workType: 'Testing',
          description: 'End to end testing with Cypress',
          hours: 6,
        },
      ],
    },
    {
      id: 'ts-week-8',
      weekNumber: 8,
      year: 2024,
      startDate: '2024-02-18',
      endDate: '2024-02-22',
      entries: [
        {
          id: 'ent-8-1',
          timesheetId: 'ts-week-8',
          date: '2024-02-18',
          projectId: 'proj-2',
          projectName: 'Mobile App',
          workType: 'Feature Development',
          description: 'Profile settings screen',
          hours: 8,
        },
        {
          id: 'ent-8-2',
          timesheetId: 'ts-week-8',
          date: '2024-02-19',
          projectId: 'proj-2',
          projectName: 'Mobile App',
          workType: 'Feature Development',
          description: 'Dark mode styling and theme switcher',
          hours: 8,
        },
        {
          id: 'ent-8-3',
          timesheetId: 'ts-week-8',
          date: '2024-02-20',
          projectId: 'proj-4',
          projectName: 'API Integration',
          workType: 'Feature Development',
          description: 'Webhook listeners',
          hours: 8,
        },
        {
          id: 'ent-8-4',
          timesheetId: 'ts-week-8',
          date: '2024-02-21',
          projectId: 'proj-5',
          projectName: 'Bug Fixes',
          workType: 'Bug fixes',
          description: 'Resolve memory leak in chart canvas',
          hours: 8,
        },
        {
          id: 'ent-8-5',
          timesheetId: 'ts-week-8',
          date: '2024-02-22',
          projectId: 'proj-6',
          projectName: 'Design System',
          workType: 'Feature Development',
          description: 'Accessible modal dialog component',
          hours: 8,
        },
      ],
    },
    {
      id: 'ts-week-9',
      weekNumber: 9,
      year: 2024,
      startDate: '2024-02-25',
      endDate: '2024-02-29',
      entries: [],
    },
    {
      id: 'ts-week-10',
      weekNumber: 10,
      year: 2024,
      startDate: '2024-03-03',
      endDate: '2024-03-07',
      entries: [
        {
          id: 'ent-10-1',
          timesheetId: 'ts-week-10',
          date: '2024-03-03',
          projectId: 'proj-3',
          projectName: 'Dashboard Development',
          workType: 'Feature Development',
          description: 'Realtime updates using WebSockets',
          hours: 8,
        },
        {
          id: 'ent-10-2',
          timesheetId: 'ts-week-10',
          date: '2024-03-04',
          projectId: 'proj-3',
          projectName: 'Dashboard Development',
          workType: 'Feature Development',
          description: 'Data virtualization for large tables',
          hours: 8,
        },
      ],
    },
  ];

  return timesheetData.map((ts) => {
    const totalHours = calculateTotalHours(ts.entries);
    return {
      ...ts,
      totalHours,
      status: getTimesheetStatus(totalHours),
    };
  });
}

export const INITIAL_TIMESHEETS: Timesheet[] = createInitialTimesheets();
